### ISSUE TITLE
Home page not loading, product list 500

### ISSUE THREAD

**Issue by johnmarkredding** [c-rose-g/EUPHORIA#68]
Hey Cece, I have an issue viewing site functionality. I see a flash of the header, and then it all goes white.

Suerte!

![Screen Shot 2023-07-27 at 6 38 35 PM](https://github.com/c-rose-g/EUPHORIA/assets/15619295/45ff3cbf-58cf-48be-8149-d9732e183f5f)

**Comment by c-rose-g** [comment]
Thank you, John for letting me know! I am looking into it now.

**Comment by c-rose-g** [comment]
ReadMe website link has been updated to the *new* website link.
